import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { describe, it, expect } from "vitest";

const { maybeBuildEvolveRecommendation } = await import("../evolveTrigger.js");

function createProjectRoot(): string {
  const projectRoot = mkdtempSync(join(tmpdir(), "aif-evolve-trigger-"));
  const aifDir = resolve(projectRoot, ".ai-factory");
  const patchesDir = resolve(aifDir, "patches");
  const evolutionsDir = resolve(aifDir, "evolutions");
  mkdirSync(patchesDir, { recursive: true });
  mkdirSync(evolutionsDir, { recursive: true });
  writeFileSync(
    resolve(aifDir, "config.yaml"),
    ["paths:", "  patches: .ai-factory/patches/", "  evolutions: .ai-factory/evolutions/"].join(
      "\n",
    ),
    "utf8",
  );
  return projectRoot;
}

function writePatch(projectRoot: string, name: string, content: string): void {
  writeFileSync(resolve(projectRoot, ".ai-factory", "patches", name), content, "utf8");
}

describe("maybeBuildEvolveRecommendation", () => {
  it("returns recommendation once when >=5 fix patches are detected and debounces further runs", () => {
    // BR: BR-trigger.automation.failure-recovery
    // FR: REQ-FR-pipeline.plan.refine-plan-second-pass
    // NFR: REQ-NFR-ops.observability.audit-trail-completeness
    // KI: KI-14
    const projectRoot = createProjectRoot();
    for (let i = 1; i <= 5; i += 1) {
      writePatch(projectRoot, `2026-09-22-0${i}.md`, `# Patch ${i}\n\nSource: /aif-fix\n`);
    }

    const first = maybeBuildEvolveRecommendation(projectRoot);
    const second = maybeBuildEvolveRecommendation(projectRoot);

    expect(first).toContain("Consider running /aif-evolve");
    expect(second).toBeNull();
  });

  it("returns null when fix patch threshold is not reached", () => {
    // BR: BR-trigger.automation.failure-recovery
    // FR: REQ-FR-pipeline.plan.refine-plan-second-pass
    // NFR: REQ-NFR-ops.observability.audit-trail-completeness
    // KI: KI-14
    const projectRoot = createProjectRoot();
    for (let i = 1; i <= 4; i += 1) {
      writePatch(projectRoot, `2026-09-22-1${i}.md`, `# Patch ${i}\n\nSource: /aif-fix\n`);
    }

    const result = maybeBuildEvolveRecommendation(projectRoot);
    expect(result).toBeNull();
  });

  it("persists debounce state under paths.evolutions", () => {
    // BR: BR-trigger.automation.failure-recovery
    // FR: REQ-FR-pipeline.plan.refine-plan-second-pass
    // NFR: REQ-NFR-ops.observability.audit-trail-completeness
    // KI: KI-14
    const projectRoot = createProjectRoot();
    for (let i = 1; i <= 6; i += 1) {
      writePatch(
        projectRoot,
        `2026-09-22-2${i}.md`,
        `# Patch ${i}\n\nFix plan generated by aif-fix\n`,
      );
    }

    maybeBuildEvolveRecommendation(projectRoot);

    const statePath = resolve(
      projectRoot,
      ".ai-factory",
      "evolutions",
      "patch-cursor.evolve-trigger.json",
    );
    expect(existsSync(statePath)).toBe(true);
    const raw = readFileSync(statePath, "utf8");
    const parsed = JSON.parse(raw) as { lastPatchCount: number; lastSuggestedAt: string | null };
    expect(parsed.lastPatchCount).toBe(6);
    expect(typeof parsed.lastSuggestedAt).toBe("string");
  });
});
