export {
  BranchIsolationError,
  assertCurrentBranch,
  assertWorkingTreeClean,
  branchExists,
  buildBranchName,
  buildProjectWorktreeSegment,
  buildTaskWorktreePath,
  describeDirtyWorkingTree,
  ensureFeatureBranch,
  ensureTaskWorktree,
  getCurrentBranch,
  isBranchIsolationError,
  isGitRepo,
  listChangedFiles,
  listWorktrees,
  projectSupportsTaskWorktrees,
  projectUsesSharedBranchIsolation,
  resolveWorktreeRoot,
  restorePersistedBranch,
  slugifyTitle,
  validateBranchName,
  workingTreeClean,
  type BuildTaskWorktreePathInput,
  type EnsureFeatureBranchInput,
  type EnsureFeatureBranchResult,
  type EnsureTaskWorktreeInput,
  type EnsureTaskWorktreeResult,
  type RestorePersistedBranchInput,
  type WorktreeEntry,
} from "@aif/shared";
