// Browser-safe exports — no Node.js dependencies (no better-sqlite3, pino, etc.)

export {
  TASK_STATUSES,
  type TaskStatus,
  PARTICIPANT_ROLES,
  type ParticipantRole,
  EXECUTION_OWNERS,
  type ExecutionOwner,
  AUDIT_ACTOR_KINDS,
  type AuditActorKind,
  type AutoQueueCommitStatus,
  AUTO_REVIEW_STRATEGIES,
  type AutoReviewStrategy,
  AUTO_REVIEW_FINDING_SOURCES,
  type AutoReviewFindingSource,
  type AutoReviewFinding,
  type AutoReviewState,
  type Project,
  type GitHubEligibility,
  type GitHubRepositoryConnection,
  type GitHubIssueCommentSnapshot,
  type GitHubIssueSnapshot,
  type GitHubIssueLink,
  type GitLabEligibility,
  type GitLabRepositoryConnection,
  type GitLabIssueCommentSnapshot,
  type GitLabIssueSnapshot,
  type GitLabIssueLink,
  type UpdateProjectOrganizationInput,
  type CreateProjectInput,
  type AppSettings,
  type UpdateAppSettingsInput,
  type Task,
  type TaskListItem,
  type ParticipantSummary,
  type Participant,
  type AuthSessionState,
  type CreateParticipantInput,
  type UpdateParticipantInput,
  type ResetParticipantPasswordInput,
  type TaskAssigneeSummary,
  type TaskPermissions,
  type AuditActor,
  type AuditEvent,
  type TaskExecutorHistoryEntry,
  type TaskOwnership,
  type HandoffTaskInput,
  type TaskOwnershipConflictCode,
  type TaskOwnershipConflict,
  type ProjectTaskPreview,
  type ProjectTaskOverview,
  type CreateTaskInput,
  type UpdateTaskInput,
  type TaskComment,
  type TaskCommentAttachment,
  type CreateTaskCommentInput,
  TASK_EVENTS,
  type TaskEvent,
  type TaskEventInput,
  type ReorderTaskInput,
  type WsEventType,
  type WsEvent,
  type RoadmapCompletePayload,
  type RoadmapErrorPayload,
  type TaskCommitPayload,
  type TaskQaPayload,
  type RuntimeLimitBroadcastPayload,
  type ParticipantBroadcastPayload,
  type ParticipantSessionRevokedPayload,
  type TaskOwnershipBroadcastPayload,
  type TaskCommentBroadcastPayload,
  type TaskHeartbeatPayload,
  type TaskUsagePayload,
  type TaskCurrentTool,
  type ChatMessage,
  type ChatMessageAttachment,
  type ChatAttachment,
  type ChatRequest,
  type ChatStreamTokenPayload,
  type ChatDonePayload,
  type ChatErrorPayload,
  type ChatAction,
  type ChatActionCreateTask,
  isRuntimeTransport,
  RUNTIME_TRANSPORTS,
  RuntimeTransport,
  type RuntimeDescriptor,
  type RuntimeProfileUsage,
  type RuntimeProfile,
  type CreateRuntimeProfileInput,
  type UpdateRuntimeProfileInput,
  type EffectiveRuntimeProfileSource,
  type EffectiveRuntimeProfileSelection,
  RuntimeLimitSource,
  RuntimeLimitStatus,
  RuntimeLimitPrecision,
  RuntimeLimitScope,
  type RuntimeLimitWindow,
  type RuntimeLimitSnapshot,
  type RuntimeLimitEventPayload,
  type WarmupBroadcastPayload,
  type ChatSessionSource,
  type ChatSession,
  type CreateChatSessionInput,
  type UpdateChatSessionInput,
  type ChatSessionMessage,
} from "./types.js";

export {
  STATUS_CONFIG,
  ORDERED_STATUSES,
  WARMUP_TARGETS,
  WARMUP_WORKFLOW_KINDS,
  DEFAULT_WARMUP_TARGET,
  isWarmupWorkflowKind,
  type WarmupTarget,
  type WarmupWorkflowKind,
  type WarmupProfileMode,
} from "./constants.js";
export {
  resolveTaskAction,
  resolveTaskPermissions,
  HUMAN_ACTIONS_BY_STATUS,
  type TaskActionContext,
  type TaskActionDeniedCode,
  type TaskPolicyView,
  type TransitionPatch,
  type TransitionResult,
} from "./stateMachine.js";
export { withTimeout } from "./withTimeout.js";
export {
  buildRuntimeLimitSignature,
  normalizeRuntimeLimitSnapshot,
  redactProviderText,
  redactProviderTextForLogs,
  resolveRuntimeLimitFutureHint,
  sanitizeRuntimeLimitSnapshotForExposure,
  sanitizeProviderMeta,
  selectViolatedWindowForExactThreshold,
  type RuntimeLimitFutureHint,
  type RuntimeLimitFutureHintSource,
  type RuntimeLimitSnapshotExposure,
  type SafeRuntimeErrorCategory,
  type SafeRuntimeErrorReason,
} from "./runtimeLimitUtils.js";

// Plan path utilities (pure functions, browser-safe — separate module with no Node.js deps)
export { slugify, generatePlanPath } from "./planPath.js";
export type { GeneratePlanPathOptions } from "./planPath.js";

// Sync types (browser-safe subset — types only, no Node.js logger dependency)
export type { SyncDirection, ConflictResolution, SyncEvent, PlanAnnotation } from "./sync.js";

// Planner mode defaults (pure, browser-safe)
export { defaultsForMode } from "./plannerDefaults.js";
export type { PlannerMode, PlannerFlagDefaults } from "./plannerDefaults.js";
